default: &BASE
  adapter: postgresql
  username: pgmacbookair
  password: mac6154
  encoding: utf8
  min_messages: warning
  pool: 25
development:
  <<: *BASE
  database: little_bits_dev
test:
  <<: *BASE
  database: little_bits_test

